const fs = require('fs').promises;
const path = require('path');
const { exec } = require('child_process');
const { promisify } = require('util');
const execAsync = promisify(exec);

// Setup Nginx configuration for a tenant
const setupNginxConfig = async (subdomain, tenantId) => {
  try {
    const configContent = generateNginxConfig(subdomain, tenantId);
    const configPath = `/etc/nginx/sites-available/${subdomain}`;
    
    // Write configuration file
    await fs.writeFile(configPath, configContent);
    
    // Create symbolic link to enable the site
    await execAsync(`ln -sf ${configPath} /etc/nginx/sites-enabled/`);
    
    // Test Nginx configuration
    const { stderr } = await execAsync('nginx -t');
    if (stderr && !stderr.includes('test is successful')) {
      throw new Error(`Nginx configuration test failed: ${stderr}`);
    }
    
    // Reload Nginx
    await execAsync('nginx -s reload');
    
    console.log(`Nginx configuration created for tenant: ${subdomain}`);
    return true;
    
  } catch (error) {
    console.error('Error setting up Nginx configuration:', error);
    throw error;
  }
};

// Generate Nginx configuration for a tenant
const generateNginxConfig = (subdomain, tenantId) => {
  const domain = `${subdomain}.${process.env.MAIN_DOMAIN}`;
  
  return `# Nginx configuration for ${domain}
# Auto-generated by Tenant Manager

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    
    # Redirect HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${domain};
    
    # SSL Configuration
    ssl_certificate /etc/nginx/ssl/${domain}.crt;
    ssl_certificate_key /etc/nginx/ssl/${domain}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Root directory
    root /var/www/tenants/${subdomain};
    index index.php index.html index.htm;
    
    # Log files
    access_log /var/log/nginx/${domain}_access.log;
    error_log /var/log/nginx/${domain}_error.log;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private must-revalidate auth;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/xml+rss
        application/json;
    
    # WordPress specific configuration
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    
    # Handle PHP files
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param TENANT_ID "${subdomain}";
        fastcgi_param TENANT_DOMAIN "${domain}";
        include fastcgi_params;
    }
    
    # Deny access to sensitive files
    location ~ /\. {
        deny all;
    }
    
    location ~ /(wp-config.php|wp-config-sample.php|readme.html|license.txt|wp-admin/install.php) {
        deny all;
    }
    
    # Cache static files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    
    # WordPress uploads
    location ~* /wp-content/uploads/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    
    # WordPress admin area
    location /wp-admin/ {
        auth_basic "Admin Area";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
    
    # WooCommerce specific
    location /wc-api/ {
        try_files $uri $uri/ /index.php?$args;
    }
    
    # Custom error pages
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    
    location = /50x.html {
        root /usr/share/nginx/html;
    }
    
    # Rate limiting
    limit_req_zone $binary_remote_addr zone=wordpress:10m rate=10r/s;
    limit_req zone=wordpress burst=20 nodelay;
    
    # File upload limits
    client_max_body_size 64M;
    client_body_timeout 60s;
    client_header_timeout 60s;
    
    # Proxy settings for external APIs
    location /api/ {
        proxy_pass http://tenant-manager:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\\n";
        add_header Content-Type text/plain;
    }
}`;
};

// Remove Nginx configuration for a tenant
const removeNginxConfig = async (subdomain) => {
  try {
    const configPath = `/etc/nginx/sites-available/${subdomain}.${process.env.MAIN_DOMAIN}`;
    const enabledPath = `/etc/nginx/sites-enabled/${subdomain}.${process.env.MAIN_DOMAIN}`;
    
    // Remove symbolic link
    await fs.unlink(enabledPath).catch(() => {});
    
    // Remove configuration file
    await fs.unlink(configPath).catch(() => {});
    
    // Test and reload Nginx
    await execAsync('nginx -t');
    await execAsync('nginx -s reload');
    
    console.log(`Nginx configuration removed for tenant: ${subdomain}`);
    return true;
    
  } catch (error) {
    console.error('Error removing Nginx configuration:', error);
    throw error;
  }
};

// Update Nginx configuration for a tenant
const updateNginxConfig = async (subdomain, tenantId) => {
  try {
    await removeNginxConfig(subdomain);
    await setupNginxConfig(subdomain, tenantId);
    
    console.log(`Nginx configuration updated for tenant: ${subdomain}`);
    return true;
    
  } catch (error) {
    console.error('Error updating Nginx configuration:', error);
    throw error;
  }
};

// Generate SSL certificate for a tenant
const generateSSLCertificate = async (subdomain) => {
  try {
    const domain = `${subdomain}.${process.env.MAIN_DOMAIN}`;
    const certPath = `/etc/nginx/ssl/${domain}.crt`;
    const keyPath = `/etc/nginx/ssl/${domain}.key`;
    
    // Create SSL directory if it doesn't exist
    await fs.mkdir('/etc/nginx/ssl', { recursive: true });
    
    // Generate self-signed certificate (for development)
    // In production, you should use Let's Encrypt or a proper CA
    await execAsync(`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${keyPath} -out ${certPath} -subj "/C=US/ST=State/L=City/O=Organization/CN=${domain}"`);
    
    console.log(`SSL certificate generated for domain: ${domain}`);
    return {
      cert: certPath,
      key: keyPath
    };
    
  } catch (error) {
    console.error('Error generating SSL certificate:', error);
    throw error;
  }
};

// Setup Let's Encrypt SSL certificate
const setupLetsEncryptSSL = async (subdomain) => {
  try {
    const domain = `${subdomain}.${process.env.MAIN_DOMAIN}`;
    
    // Install certbot if not already installed
    await execAsync('which certbot || apt-get update && apt-get install -y certbot python3-certbot-nginx');
    
    // Generate certificate using certbot
    await execAsync(`certbot --nginx -d ${domain} --non-interactive --agree-tos --email ${process.env.SSL_EMAIL} --redirect`);
    
    console.log(`Let's Encrypt SSL certificate generated for domain: ${domain}`);
    return true;
    
  } catch (error) {
    console.error('Error setting up Let\'s Encrypt SSL:', error);
    throw error;
  }
};

// Get Nginx status
const getNginxStatus = async () => {
  try {
    const { stdout } = await execAsync('nginx -t');
    const isConfigValid = !stdout.includes('failed');
    
    const { stdout: statusOutput } = await execAsync('systemctl is-active nginx');
    const isRunning = statusOutput.trim() === 'active';
    
    return {
      configValid: isConfigValid,
      isRunning,
      status: isRunning ? 'running' : 'stopped'
    };
    
  } catch (error) {
    console.error('Error getting Nginx status:', error);
    return {
      configValid: false,
      isRunning: false,
      status: 'error'
    };
  }
};

// Reload Nginx configuration
const reloadNginx = async () => {
  try {
    await execAsync('nginx -t');
    await execAsync('nginx -s reload');
    
    console.log('Nginx configuration reloaded successfully');
    return true;
    
  } catch (error) {
    console.error('Error reloading Nginx:', error);
    throw error;
  }
};

// Get all active sites
const getActiveSites = async () => {
  try {
    const { stdout } = await execAsync('ls /etc/nginx/sites-enabled/');
    const sites = stdout.trim().split('\n').filter(site => site.length > 0);
    
    return sites.map(site => site.replace('.conf', ''));
    
  } catch (error) {
    console.error('Error getting active sites:', error);
    return [];
  }
};

// Check if site is enabled
const isSiteEnabled = async (subdomain) => {
  try {
    const enabledPath = `/etc/nginx/sites-enabled/${subdomain}.${process.env.MAIN_DOMAIN}`;
    await fs.access(enabledPath);
    return true;
    
  } catch (error) {
    return false;
  }
};

module.exports = {
  setupNginxConfig,
  removeNginxConfig,
  updateNginxConfig,
  generateSSLCertificate,
  setupLetsEncryptSSL,
  getNginxStatus,
  reloadNginx,
  getActiveSites,
  isSiteEnabled
};
